services:
  go_app:
    build:
      context: ..
      dockerfile: build/Dockerfile.service
    container_name: go_app
    # expose:
    #   - 6971:6969
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"  # HTTP
      - "443:443"  # HTTPS
    volumes:
      - ../ssl:/etc/nginx/ssl           # Mount SSL certificates
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Mount Nginx config
    networks:
      - app_network
    depends_on:
      - go_app

networks:
  app_network:
