services:
  go_app:
    build:
      context: ..
      dockerfile: build/Dockerfile.service
    container_name: go_app
    # expose:
    #   - 6971:6969
    networks:
      - app_network
    deploy:
      resources:
        limits:
          memory: 512M # max mem for container 
        reservations:
          memory: 512M # memory reserved 
    volumes:
      - ../data:/app/data # Mount local `data` directory to `/app/data` in the container
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"  # HTTP
      - "443:443"  # HTTPS
    volumes:
      - ./ssl:/etc/nginx/ssl           # Mount SSL certificates
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Mount Nginx config
    networks:
      - app_network
    depends_on:
      - go_app

networks:
  app_network:
