INSERT INTO 
    bots (guild, username, avatarurl, bannerurl, createdat, author, status, issinger)
VALUES 
    ('$dads', 'StoufBot', 'https://picsum.photos/200/300', 'None', '2023-04-25', 'kyri56xcaesar', 'active', 0), -- id 1 25-4-2023
    ('$dads', 'KokeBot', 'https://picsum.photos/200/400', 'None', '2023-04-25', 'kyri56xcaesar', 'active', 0), -- id 2 25-4-2023
    ('$dads', 'SAKBot', 'https://picsum.photos/300/400', 'None', '2023-04-25', 'kyri56xcaesar', 'active', 1), -- id 3 25-4-2023
    ('$dads', 'VassanoBot', 'https://picsum.photos/300/300', 'None', '2023-04-25', 'kyri56xcaesar', 'active', 0), -- id 4 25-4-2023
    ('$dads', 'StratigosBot', 'https://picsum.photos/200/200', 'None', '2023-04-25', 'kyri56xcaesar', 'sleeper', 0), -- id 5 25-4-2023
    ('$dads', 'HayateBot', 'https://picsum.photos/500/500', 'None', '2023-03-04', 'kyri56xcaesar', 'abandoned', 1), -- id 6 4-3-2023
    ('$dads', 'SnakeBot', 'https://picsum.photos/400/500', 'None', '2024-07-25', 'kyri56xcaesar', 'inprogress', 0), -- id 7 25-7-2024
    ('$dads', 'ModiasBot', 'https://picsum.photos/500/400', 'None', '2024-08-02', 'kyri56xcaesar', 'active', 0) -- id 8 2-8-2024
;


INSERT INTO
    lines (bid, phrase, author, toid, ltype)
VALUES
    (2, "TIIIIIIIII", "kyri", "all", "typical"),
    (2, "geia sou mikro pouleriko", "kyri", "all", "typical"),
    (2, "modia gamiesai", "kyri", "all", "typical"),
    (2, "geia sou dhmhtrh", "kyri", "all", "typical"),
    (2, "gamo to soi moy", "kyri", "all", "typical"),
    (2, "ksypnate reeeeeiii", "kyri", "all", "typical"),
    (2, "ksafnika lupothimisa", "kyri", "all", "typical"),
    (2, "epesa pano sto pomolo", "kyri", "all", "typical"),
    (2, "exw faei camp", "kyri", "all", "typical"),
    (2, "arneitai na paiksei", "kyri", "all", "typical"),
    (2, "DES TI KANEI O JUNGLER MOY!", "kyri", "all", "typical"),
    (2, "noliiii, pame kana duo??", "kyri", "all", "typical"),
    (2, "den exw aderfia", "kyri", "all", "typical"),
    (2, "modia. I POUTANA I manas", "kyri", "all", "typical"),
    (2, "aggele pame duo???", "kyri", "all", "typical"),
    (2, "glistrisa se kati ladia kai anoiksa to pigouni moy bro", "kyri", "all", "typical"),
    (2, "otan moy vazoyn duskola antapokrinomai", "kyri", "all", "typical"),
    (1, "ola gia mia trupa ginontai", "kyri", "all", "typical"),
    (1, "voliiiiii", "kyri", "all", "typical"),
    (1, "bmw me collector", "kyri", "all", "typical"),
    (1, "ayrio pao diamon", "kyri", "all", "typical"),
    (1, "simerini efimerida\n exei kialo filo\to simera exo 17 clips 1vs 3 kai 1vs 4", "kyri", "all", "typical"), -- Missing comma added
    (4, "Kalhspera kai kali vradia edw me ton aderfo fofota", "kyri", "all", "typical"),
    (4, "gamo ton karioli ton OTE apo tis 7 to prwi mexri twra den eixa internet gamo tinpanagia tous prwi prwi", "kyri", "all", "typical"),
    (4, "gamw tis manes tous", "kyri", "all", "typical"),
    (4, "simera anastithike o bines", "kyri", "all", "typical"),
    (4, "me trexoyn oi traktores", "kyri", "all", "typical"),
    (4, "ksekinise to praktorio", "kyri", "all", "typical"),
    (4, "ff x9 matchfixers/griefers/hostagers", "kyri", "all", "typical"),
    (4, "epesa PLAT apo master 230 lp se mia nuxta", "kyri", "all", "typical"),
    (4, "pame vraxous gt me trexoyn ta mpastarda", "kyri", "all", "typical"),
    (4, "koke gamw tinmana sou vlaka", "kyri", "all", "typical"),
    (4, "me treksan tapromo mexri diamond 0 lp", "kyri", "all", "typical"),
    (4, "legit ama den paw master to kleinw kai 3 meres naparei", "kyri", "all", "typical"), -- Extra space removed before "naparei"
    (4, "na se paw mia volta aptis kuries?", "kyri", "all", "typical"),
    (4, "o mikros apo tin pisw porta", "kyri", "all", "typical"),
    (4, "me trexei o lazer", "kyri", "all", "typical"),
    (3, "eimai gia tin poutsa...", "kyri", "all", "typical"),
    (3, "wRaIo dAmAgE", "kyri", "all", "typical"),
    (3, "ADERFIA MOYY!!!", "kyri", "all", "typical"),
    (3, "nai alla tiwra.gr", "kyri", "all", "typical"),
    (8, "Εμμανουήλ, τι παίζεις φίλε?", "siopis", "manos", "typical"),
    (8, "Λούγκα δεν έχει", "siopis", "kyri", "typical"),
    (8, "Ποιός είναι αυτός ο όμορφος?", "siopis", "modias", "typical"),
    (8, "Εσύ δεν έχεις σχολείο αύριο?", "siopis", "mikras", "typical"),
    (8, "Κόουτς... γαμιέσαι", "siopis", "siopis", "typical"),
    (8, "Ήρεμα Θάνο", "siopis", "sak", "typical"),
    (8, "Δεν είμαστε το Χαμόγελο του Παιδιού εδώ", "siopis", "koke", "typical"),
    (8, "Καλώς τ'αρχδία μας", "siopis", "kef", "typical"),
    (8, "Σκάσε καραφλέ", "siopis", "nasos", "typical"),
    (8, "ΙΝΤΙΜΙΝΤΕΙΤ ΣΟΛΟΚΙΟΥ... ΜΑΑΑΛΙΣΤΑ", "siopis", "mg", "typical"),
    (8, "Μα καλά δε μαξάρεις Flash?", "siopis", "yaku", "typical"),
    (8, "Μακράν ο χειρότερος τραγουδιστής που δεν έχω ακούσει αδερφέ", "siopis", "mike", "typical"),
    (8, "Έλα βούλωσ'το, πάνε παίξε μυρμήγκια", "siopis", "takas", "typical"),
    (8, "Ενδιαφέρον θεωρία", "siopis", "all", "typical"),
    (8, "Το μουνί της μάνας σου", "siopis", "all", "typical"),
    (8, "Για", "siopis", "all", "typical"),
    (8, "ΘΑ ΦΥΓΩ, ΤΟ 'ΧΩ ΞΑΝΑΚΑΝΕΙ", "siopis", "all", "typical"),
    (8, "Θα περιμένω πολύυυ?", "siopis", "all", "typical"),
    (8, "Δεν έχει καθόλου δροσιά", "siopis", "all", "typical"),
    (8, "Δεξί αριστερό", "siopis", "all", "typical"),
    (8, "CLEAVE THROUGH THEM AATROX", "siopis", "all", "typical"),
    (8, "Και τα μαρούλια μέσα", "siopis", "all", "typical"),
    (8, "Έλα μη με τιλτάρεις τώρα", "siopis", "all", "typical"),
    (8, "Sydney Sweeney μόνο", "siopis", "all", "typical"),
    (8, "Rap god Modias", "siopis", "all", "typical"),
    (8, "Δες τι ήρωα έχει φτιάξει η Riot", "siopis", "all", "typical"),
    (8, "Το Poppy τι είναι, τι είναι?", "siopis", "all", "typical"),
    (8, "Εεε irrelevant", "siopis", "all", "typical"),
    (8, "Ένα, δύο... ΤΕΣΣΕΡΑ", "siopis", "all", "typical"),
    (8, "Ωωωωω στ'αρχιδια μας", "siopis", "all", "typical"), -- Missing comma added
    (8, "Όντως?", "siopis", "all", "typical"),
    (8, "Είναι μια αλήθεια αυτό", "siopis", "all", "typical"),
    (8, "Χεχεεε βλάκααα", "siopis", "all", "typical"),
    (8, "Βέεεεεεεεεβαια", "siopis", "all", "typical"),
    (8, "Θα με κάνει gank ο J4", "siopis", "all", "typical"), -- Missing comma added
    (2, "Koke", "kyri", "all", "trigger"),
    (2, "koke", "kyri", "all", "trigger"),
    (2, "KOKE", "kyri", "all", "trigger"),
    (2, "ela", "kyri", "all", "trigger"),
    (2, "0/100", "kyri", "all", "trigger"),
    (2, "3 cs", "kyri", "all", "trigger"),
    (2, "ELA", "kyri", "all", "trigger"),
    (2, "OUELA", "kyri", "all", "trigger"),
    (2, "xontre", "kyri", "all", "trigger"),
    (2, "XONTRE", "kyri", "all", "trigger"),
    (2, "gamiesai", "kyri", "all", "trigger"),
    (2, "gamiese", "kyri", "all", "trigger"),
    (2, "GAMIESAI", "kyri", "all", "trigger"),
    (2, "GAMIESE", "kyri", "all", "trigger"),
    (2, "elaaaa", "kyri", "all", "trigger"),
    (2, "elaa", "kyri", "all", "trigger"),
    (2, "elaaa", "kyri", "all", "trigger"),
    (2, "o palios", "kyri", "all", "trigger"),
    (2, "O PALIOS", "kyri", "all", "trigger"),
    (2, "pouleriko", "kyri", "all", "trigger"),
    (2, "lb", "kyri", "all", "trigger"),
    (2, "Ela", "kyri", "all", "trigger"),
    (2, "Xontre", "kyri", "all", "trigger"),
    (2, "Gamiesai", "kyri", "all", "trigger"),
    (2, "Pouleriko", "kyri", "all", "trigger"),
    (2, "poyleriko", "kyri", "all", "trigger"),
    (2, "Poyleriko", "kyri", "all", "trigger"),
    (1, "volibear", "kyri", "all", "trigger"),
    (1, "voli", "kyri", "all", "trigger"),
    (1, "teo", "kyri", "all", "trigger"),
    (1, "teo123stouf", "kyri", "all", "trigger"),
    (1, "teo123", "kyri", "all", "trigger"),
    (1, "stouf", "kyri", "all", "trigger"), -- Missing comma added
    (1, "VOLI", "kyri", "all", "trigger"),
    (1, "Voli", "kyri", "all", "trigger"),
    (1, "VOLIBEAR", "kyri", "all", "trigger"),
    (1, "Volibear", "kyri", "all", "trigger"),
    (1, "!Voli", "kyri", "all", "trigger"),
    (1, "!VOLI", "kyri", "all", "trigger"),
    (1, "!voli", "kyri", "all", "trigger"),
    (1, "arkouda", "kyri", "all", "trigger"), -- Missing comma added
    (1, "@teo", "kyri", "all", "trigger"),
    (1, "ARKOUDA", "kyri", "all", "trigger"),
    (1, "Arkouda", "kyri", "all", "trigger"),
    (4, "yorick", "kyri", "all", "trigger"),
    (4, "praktoras", "kyri", "all", "trigger"),
    (3, "Den exei nohma i yparksi xwris ton mpakaliaro...", "kyri", "all", "sad"),
    (3, "xwris ton mpakaliaro periplaniemai askopa se ena axanes sumpan...", "kyri", "all", "sad"),
    (3, "afougrazomai tis stigmes poy zisame me ton mpakaliaro kai den tis xortainw..", "kyri", "all", "sad");

